FROM quay.io/fedora/fedora-bootc:43

# Install some standard packages
RUN <<EOF
dnf install -y greenboot greenboot-default-health-checks
dnf clean all
rm -rf /var/log/dnf5.log /var/cache/libdnf5 /var/lib/dnf
EOF

RUN bootc container lint